jwt:
  secret: ${JWT_SECRET}

app:
  admin:
    username: ${ADMIN_USERNAME}
    firstname: ${ADMIN_FIRSTNAME}
    lastname: ${ADMIN_LASTNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  upload:
    dir: ${UPLOAD_DIR}
    
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    tls: ${MAIL_TLS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  