jwt:
  secret: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQ= 

app:
  admin:
    username: admin
    firstname: System
    lastname: Administrator
    email: admin@localmarket.com
    password: ${ADMIN_PASSWORD:admin123}  # Use env variable or default
  upload:
    dir: uploads/products